---
name: "RequestsAddon"
guid: "b0bef419-e5b8-439d-a6a5-9b96949cbe7e"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Allows setting of URL for request tab"
description: >
 Allows setting of URL for request tab
category: "Other"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.RequestsAddon.dll"
changelog: >
  Inital iteration
